dependencies:
  - name: cassandra
    version: ^0.13.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: provisionDataStore.cassandra
  - name: elasticsearch
    version: ^7.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
