{{- if and .Values.agent.enabled .Values.serviceAccounts.agent.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.agent.name" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
{{- end -}}
