{{- if and .Values.query.enabled .Values.serviceAccounts.query.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.query.serviceAccountName" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
{{- end -}}
