name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      # See https://github.com/helm/chart-releaser-action/issues/6
      - name: Initialize Helm
        run: helm init --client-only

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/
          helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.1
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
